// Generated by gencpp from file rc_car/Command.msg
// DO NOT EDIT!


#ifndef RC_CAR_MESSAGE_COMMAND_H
#define RC_CAR_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rc_car
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : speed(0.0)
    , dir(0.0)
    , modeAuto(false)  {
    }
  Command_(const ContainerAllocator& _alloc)
    : speed(0.0)
    , dir(0.0)
    , modeAuto(false)  {
    }



   typedef float _speed_type;
  _speed_type speed;

   typedef float _dir_type;
  _dir_type dir;

   typedef uint8_t _modeAuto_type;
  _modeAuto_type modeAuto;




  typedef boost::shared_ptr< ::rc_car::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rc_car::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::rc_car::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::rc_car::Command > CommandPtr;
typedef boost::shared_ptr< ::rc_car::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rc_car::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rc_car::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rc_car

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rc_car': ['/home/victorien/catkin_ws/src/rc_car/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rc_car::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rc_car::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rc_car::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rc_car::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rc_car::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rc_car::Command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rc_car::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34ba426152292a9bf51e1381d9b3352b";
  }

  static const char* value(const ::rc_car::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34ba426152292a9bULL;
  static const uint64_t static_value2 = 0xf51e1381d9b3352bULL;
};

template<class ContainerAllocator>
struct DataType< ::rc_car::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rc_car/Command";
  }

  static const char* value(const ::rc_car::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rc_car::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 speed\n\
float32 dir\n\
bool modeAuto\n\
";
  }

  static const char* value(const ::rc_car::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rc_car::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.dir);
      stream.next(m.modeAuto);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rc_car::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rc_car::Command_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "dir: ";
    Printer<float>::stream(s, indent + "  ", v.dir);
    s << indent << "modeAuto: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.modeAuto);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RC_CAR_MESSAGE_COMMAND_H
