#define PWM_DC_MOTOR_FREQ 1000
#define DC_MOTOR_SPEED_MAX 10.0
#define DC_MOTOR_SPEED_MIN 0.0
#define SPEED_COEF_MAX 1.0
#define SPEED_COEF_MIN 0.0

#define PWM_SERVOMOTOR_FREQ 1000
#define SERVOMOTOR_ANGLE_MAX 45.0
#define SERVOMOTOR_ANGLE_MIN -45.0
#define DIR_COEF_MAX 1.0
#define DIR_COEF_MIN 0.0